export const resData = [
    {
        "id":"1",
        "pid":"0",
        "name":"指标库",
        "path":"1",
        "org_id":"1",
        "create_by":"644",
        "update_by":"644",
        "create_time":"1545276993",
        "update_time":"1545276993",
        "value":"1",
        "key":"1",
        "title":"指标库",
        "is_folder":1,
        "gather":[
            {
                "id":"1",
                "name":"张会喜",
                "is_folder":0
            },
            {
                "id":"95",
                "name":"6666",
                "is_folder":0
            },
            {
                "id":"96",
                "name":"222",
                "is_folder":0
            }
        ],
        "children":[
            {
                "id":"2",
                "pid":"1",
                "name":"指标库1文件夹1",
                "path":"1-2",
                "org_id":"1",
                "create_by":"0",
                "update_by":"0",
                "create_time":"0",
                "update_time":"0",
                "value":"2",
                "key":"2",
                "title":"指标库1文件夹1",
                "is_folder":1,
                "gather":[
                    {
                        "id":"2",
                        "name":"测试1",
                        "is_folder":0
                    }
                ],
                "children":[
                    {
                        "id":"3",
                        "pid":"2",
                        "name":"指标库1文件夹2",
                        "path":"1-2-3",
                        "org_id":"1",
                        "create_by":"0",
                        "update_by":"0",
                        "create_time":"0",
                        "update_time":"0",
                        "value":"3",
                        "key":"3",
                        "title":"指标库1文件夹2",
                        "is_folder":1,
                        "gather":[
                            {
                                "id":"3",
                                "name":"测试2",
                                "is_folder":0
                            },
                            {
                                "id":"93",
                                "name":"测试",
                                "is_folder":0
                            }
                        ]
                    }
                ]
            }
        ]
    }
]